### ISSUE TITLE
page indicator is not always correct

### ISSUE THREAD

**Issue by modernNeo** [CSSS/wall_e_website_fe#4]
enter `36` into the page selector and then do a backspace twice.

the page indicator displays `0` but the results are actually from page 3.

**Comment by micahdbak** [comment]
So, this isn't actually a bug, (as page 0 isn't valid for the API route), but a workaround to let users have an "empty value" in the page selector before typing again. I can make it that the 0 is grayed out, or not displayed at all, to indicate that it's waiting for further interaction from the user --- that would be more obvious. Thoughts?

**Comment by modernNeo** [comment]
is it not possible to update that field so it reverts to `1` instead of `0`?

**Comment by modernNeo** [comment]
or update it so it can never be less than 1?

**Comment by micahdbak** [comment]
Yes, very easily, but then you get stuck with writing page numbers that are 1, 1X, 1XX, ... XD

**Comment by micahdbak** [comment]
Unless you select the text, and overwrite it, but that's not intuitive for the user

**Comment by micahdbak** [comment]
Basically, the leaderboard will only make a request to the API if the page number is valid. That's why when it's equal to 0, the previous leaderboard is displayed.

**Comment by modernNeo** [comment]
> Yes, very easily, but then you get stuck with writing page numbers that are 1, 1X, 1XX, ... XD

what do you mean? when would that happen?

**Comment by micahdbak** [comment]
OK; imagine the minimum value is 1. Now you want to go to page 17, for some reason, so you type in 7. Now you backspace twice because you decide you want to see page 5. Now the value is 1; you backspace again, and it's still 1. Type in 5, now it's 15. The only way you can go to page 5 is by selecting the 1 and replacing it with 5. That's fine, but it's not intuitive, because the UI suggests you can just type in your number. With 0 as the minimum value, anything you type will become 0X, which is just X numerically, and so it works as you would expect.

**Comment by micahdbak** [comment]
But, visually it looks weird, because the leaderboard does nothing when the number is 0. So I can have the 0 turn grey to show that the value is incomplete.

**Comment by modernNeo** [comment]
I mean there is a way to solve it. if the case is indeed it displays the results for page 3 cause that was the last successful page, then what should actually be done is to display nothing but have a button in those cases that resets back to 1.

Then again, I think infinite scroll makes this whole thing moot the more I learn about the problem 🤷🏿‍♀️ ?

**Comment by micahdbak** [comment]
That's a good point actually... Clearing the leaderboard makes more sense. Also, true, infinite scroll deprecates this :rofl:

**Comment by modernNeo** [comment]
then i guess close this issue when you add the infinite scroll 😄

**Comment by modernNeo** [comment]
closing this issue as infinite scroll was added
